default_capabilities: ["builder"]
jobs:
  - name: system-toolchain
    capabilities: ["heavy"]
    tools:
      - bootstrap-system-gcc
      - system-gcc
    packages:
      - mlibc
      - mlibc-headers

  - name: icu
    tools:
      - host-icu
    packages:
      - icu

  - name: webkitgtk
    capabilities: ["heavy"]
    packages:
      - webkitgtk

  - name: image
    capabilities: ["!builder", "test-images"]
    tasks:
      - useful-image-dependencies
      - initialize-empty-image
      - remake-image
      - test-image
      - xz-image
