default_capabilities: ["builder"]
jobs:
  - name: icu
    tools:
      - host-icu
    packages:
      - icu

  - name: image
    tasks:
      - initialize-empty-image
      - remake-image
      - xz-image
