#!/bin/bash

dir=/mnt/managarm

sudo ./mount

# kernel and startup files
install -s managarm/eir/bin/eir $dir/boot/managarm
install -s managarm/thor/kernel/bin/thor $dir/boot/managarm
#install -s ../thor/user_boot/bin/user_boot $dir/boot/managarm

# userspace core components
#install -s ../../../managarm-sysroot/usr/lib/libhelix.so $dir/boot/managarm
#install -s ../thor/acpi/bin/acpi $dir/boot/managarm
#install -s ../mbus/bin/mbus $dir/boot/managarm
#install -s ../posix/subsystem/bin/posix-subsystem $dir/boot/managarm

# essential libraries
#install -s ../ld-init/linker/bin/ld-init.so $dir/boot/managarm
#install -s ../../../managarm-sysroot/usr/lib/libc.so $dir/boot/managarm
#install -s ../../../managarm-sysroot/usr/lib/libm.so $dir/boot/managarm
#install -s ../../../managarm-cross/install/x86_64-managarm/lib/libgcc_s.so.1 $dir/boot/managarm
#install -s ../../../managarm-cross/install/x86_64-managarm/lib/libstdc++.so.6 $dir/boot/managarm
#install -s ../../../managarm-sysroot/usr/lib/libz.so.1 $dir/boot/managarm
#install -s ../../../managarm-sysroot/usr/lib/libprotobuf-lite.so.10 $dir/boot/managarm
#install -s ../../../managarm-sysroot/usr/lib/libcofiber.so $dir/boot/managarm
#install -s ../../../managarm-sysroot/usr/lib/libmbus.so $dir/boot/managarm
#install -s ../../../managarm-sysroot/usr/lib/libfs.so $dir/boot/managarm

# essential drivers
#install -s ../drivers/uhci/bin/uhci $dir/boot/managarm
#install -s ../posix/init/bin/posix-init $dir/boot/managarm
#install -s ../drivers/ata/bin/ata $dir/boot/managarm
#install -s ../drivers/virtio/bin/virtio-block $dir/boot/managarm

# copy the sysroot
#cp -ru ../../../managarm-sysroot/usr $dir

sudo ./umount

