#!/bin/bash

mntlocal=
if [ -e "$1" ]; then
	dir="$1"
	echo "Copying to existing directory $dir"
else
	dir=/mnt/managarm
	echo "Mounting image to $dir"
	sudo ./mount
	mntlocal=yes
fi

# -----------------------------------------------------------------------------
# Build the initrd.
# -----------------------------------------------------------------------------

mkdir -p initrd/{lib,sbin}

# Runtime libraries.
install -s managarm/hel/bin/libhelix.so initrd/lib/
install -s managarm/ld-init/linker/bin/ld-init.so initrd/lib/
install -s mlibc/libc.so initrd/lib/
install -s mlibc/libm/bin/libm.so initrd/lib/
install -s prefixes/native-gcc/x86_64-managarm/lib/foo/libgcc_s.so.1 initrd/lib/
install -s prefixes/native-gcc/x86_64-managarm/lib/foo/libstdc++.so.6 initrd/lib/
#install -s ../../../managarm-sysroot/usr/lib/libz.so.1 initrd/
install -s system-root/usr/lib/libprotobuf-lite.so.11 initrd/lib/
install -s native/native-libcofiber/bin/libcofiber.so initrd/lib/
install -s managarm/core/virtio/bin/libvirtio_core.so initrd/lib/
install -s managarm/libarch/bin/libarch.so initrd/lib/
install -s managarm/protocols/fs/bin/libfs_protocol.so initrd/lib/
install -s managarm/protocols/hw/bin/libhw_protocol.so initrd/lib/
install -s managarm/protocols/mbus/bin/libmbus_protocol.so initrd/lib/
install -s managarm/protocols/usb/bin/libusb_protocol.so initrd/lib/

# User-space core components.
install -s managarm/mbus/bin/mbus initrd/sbin/
install -s managarm/posix/subsystem/bin/posix-subsystem initrd/sbin/
install -s managarm/posix/init/bin/posix-init initrd/sbin/

# Essential drivers.
install -s managarm/drivers/libblockfs/bin/libblockfs.so initrd/lib/

install -s managarm/drivers/uart/bin/uart initrd/sbin/
install -s managarm/drivers/gfx/intel/bin/gfx_intel initrd/sbin/
install -s managarm/drivers/gfx/bochs/bin/gfx_bochs initrd/sbin/
install -s managarm/drivers/usb/devices/hid/bin/hid initrd/sbin/
install -s managarm/drivers/usb/devices/storage/bin/storage initrd/sbin/
install -s managarm/drivers/usb/hcds/uhci/bin/uhci initrd/sbin/
install -s managarm/drivers/usb/hcds/ehci/bin/ehci initrd/sbin/
install -s managarm/drivers/virtio/bin/virtio-block initrd/sbin/
#install -s ../drivers/ata/bin/ata initrd/

# Other stuff.
install -s system-root/usr/lib/libdrm.so.2 initrd/lib/


# Actually build the initrd.
(cd initrd/ && find * | cpio -o --format newc > ../initrd.cpio)

# -----------------------------------------------------------------------------
# Copy files to the image.
# -----------------------------------------------------------------------------

mkdir -p $dir/boot/managarm
install -s managarm/eir/bin/eir $dir/boot/managarm/
install -s managarm/thor/kernel/bin/thor $dir/boot/managarm/
cp initrd.cpio $dir/boot/managarm/

# Copy the sysroot.
mkdir -p $dir/lib $dir/root $dir/usr/bin $dir/usr/lib
rsync -a --delete system-root/lib/ $dir/lib
rsync -a --delete system-root/root/ $dir/root
rsync -a --delete system-root/usr/bin/ $dir/usr/bin
rsync -a --delete system-root/usr/lib/ $dir/usr/lib
rsync -a --delete system-root/usr/libexec/ $dir/usr/libexec
rsync -a --delete system-root/usr/share/ $dir/usr/share
rsync -a --delete system-root/run/ $dir/run
cp prefixes/native-gcc/x86_64-managarm/lib/foo/libgcc_s.so.1 $dir/usr/lib
cp prefixes/native-gcc/x86_64-managarm/lib/foo/libstdc++.so.6 $dir/usr/lib

if ! [ -z $mntlocal ]; then
	sudo ./umount
fi

