#!/bin/bash

mntlocal=
if [ -n "$1" ]; then
	if [ ! -e "$1" ]; then
		echo "Directory $dir does not exist"
		exit 1
	fi
	dir="$1"
	echo "Copying to existing directory $dir"
else
	mkdir -p mountpoint/
	dir=$(realpath mountpoint/)
	echo "Mounting image to $dir"
	./mount
	mntlocal=yes
fi

# -----------------------------------------------------------------------------
# Build the initrd.
# -----------------------------------------------------------------------------

mkdir -p initrd/{bin,lib,sbin}
mkdir -p initrd/lib/kernlet

# Runtime libraries.
install -s native/native-managarm-helix/hel/bin/libhelix.so initrd/lib/
install -s system-root/usr/lib/ld.so initrd/lib/ld-init.so
install -s system-root/usr/lib/libc.so initrd/lib/
install -s system-root/usr/lib/libm.so initrd/lib/
install -s prefixes/system-gcc/x86_64-managarm/lib/foo/libgcc_s.so.1 initrd/lib/
install -s prefixes/system-gcc/x86_64-managarm/lib/foo/libstdc++.so.6 initrd/lib/
install -s system-root/usr/lib/libz.so initrd/lib/
install -s system-root/usr/lib/libprotobuf-lite.so.11 initrd/lib/
install -s native/native-libcofiber/bin/libcofiber.so initrd/lib/
install -s system-root/usr/lib/libvirtio_core.so initrd/lib/
install -s system-root/usr/lib/libarch.so initrd/lib/
install -s system-root/usr/lib/libfs_protocol.so initrd/lib/
install -s system-root/usr/lib/libhw_protocol.so initrd/lib/
install -s system-root/usr/lib/libkernlet_protocol.so initrd/lib/
install -s system-root/usr/lib/libmbus.so initrd/lib/
install -s system-root/usr/lib/libusb_protocol.so initrd/lib/

# User-space core components.
install -s system-root/usr/bin/mbus initrd/sbin/
install -s system-root/usr/bin/kernlet-c initrd/sbin/
install -s kernlet-ehci.so initrd/lib/kernlet/
install -s system-root/usr/bin/clocktracker initrd/sbin/
install -s system-root/usr/bin/posix-subsystem initrd/sbin/
install -s system-root/usr/bin/posix-init initrd/sbin/

# Essential drivers.
install -s system-root/usr/lib/libblockfs.so initrd/lib/
install -s system-root/usr/bin/uhci initrd/sbin/
install -s system-root/usr/bin/ehci initrd/sbin/
install -s system-root/usr/bin/block-ata initrd/sbin/
install -s system-root/usr/bin/storage initrd/sbin/
install -s system-root/usr/bin/virtio-block initrd/sbin/

# Essential utilities.
install -s system-root/usr/bin/runsvr initrd/bin/

# Actually build the initrd.
(cd initrd/ && find * | cpio -o --format newc > ../initrd.cpio)

# -----------------------------------------------------------------------------
# Copy files to the image.
# -----------------------------------------------------------------------------

mkdir -p $dir/boot/managarm
install -s native/native-managarm-kernel/eir/bin/eir $dir/boot/managarm/
install -s native/native-managarm-kernel/thor/kernel/bin/thor $dir/boot/managarm/
cp initrd.cpio $dir/boot/managarm/

# Copy the sysroot.
mkdir -p $dir/bin $dir/lib $dir/root $dir/usr/bin $dir/usr/lib
mkdir -p $dir/dev $dir/run $dir/sys
rsync -a --delete system-root/bin/ $dir/bin
rsync -a --delete system-root/lib/ $dir/lib
rsync -a --delete system-root/root/ $dir/root
rsync -a --delete system-root/usr/bin/ $dir/usr/bin
rsync -a --delete system-root/usr/lib/ $dir/usr/lib
rsync -a --delete system-root/usr/libexec/ $dir/usr/libexec
rsync -a --delete system-root/usr/sbin/ $dir/usr/sbin
rsync -a --delete system-root/usr/share/ $dir/usr/share
rsync -a --delete system-root/run/ $dir/run
rsync -a --delete system-root/etc/ $dir/etc
cp prefixes/system-gcc/x86_64-managarm/lib/foo/libgcc_s.so.1 $dir/usr/lib
cp prefixes/system-gcc/x86_64-managarm/lib/foo/libstdc++.so.6 $dir/usr/lib

if ! [ -z $mntlocal ]; then
	./umount
fi

