#!/bin/bash

if ! [ -d system-root ]; then
	echo "system-root/ must exist"
	exit 1
fi

mkdir -p system-root/{bin,lib,run,etc}
mkdir -p system-root/root
mkdir -p system-root/usr
mkdir -p system-root/usr/share
mkdir -p system-root/usr/share/X11
mkdir -p system-root/var
mkdir -p system-root/var/lib
mkdir -p system-root/var/lib/locate

# Create some symlinks that are currently required.
ln -sf /usr/bin/bash system-root/bin/bash
ln -sf /usr/bin/bash system-root/bin/sh
ln -sf /usr/lib/ld.so system-root/lib/ld-init.so

# Copy stuff from the host system.
rsync -a /etc/localtime system-root/etc/localtime
rsync -a --delete /usr/share/X11/xkb system-root/usr/share/X11
rsync -a --delete /usr/share/zoneinfo system-root/usr/share

