#!/bin/bash

prepend () {
	if [ -z "$1" ]; then
		echo "$2"
	else
		echo "$2:$1"
	fi
}


apply_pkg () {
	d=$1/$2

	if [ ! -e "$d" ]; then
		>&2 echo "Package '$2' not found."
		exit 1
	fi

	# process environment variables.
	if [ -e "$d/bin" ]; then
		export PATH=$(prepend "$PATH" "$d/bin")
	fi
	if [ -e "$d/lib" ]; then
		export LD_LIBRARY_PATH=$(prepend "$LD_LIBRARY_PATH" "$d/lib/x86_64-linux-gnu:$d/lib")
	fi
}

if [ $# -lt 3 ]; then
	echo "Usage: ./runpkg directory package program..."
	exit 1
fi

dir=$1
pkg=$2
program=$3
shift 3

apply_pkg $dir $pkg
exec "$program" "$@"

