#!/bin/sh

shallow="--depth 1"

if test $# -gt 0 && test "$1" = --no-shallow; then
	shallow=
	shift
fi

if test $# -ne 4; then
	echo "Usage: ./touch-if-fetch [--no-shallow] tag_file directory repository ref"
	exit 1
fi

fetched=no

if ! test -d $2; then
	if ! git clone -b $4 $shallow $3 $2; then
		exit $?
	fi
	fetched=yes
fi

if ! git -C $2 show-ref -q $4; then
	if ! git -C $2 fetch origin $4; then
		exit $?
	fi
	fetched=yes
fi

if test $fetched = yes || ! test -e $1; then
	touch $1
fi

