#!/bin/bash

set -uxe

if [ -n "${USE_LOOPBACK:-}" ]; then
	umount mountpoint/
	losetup -d "$(cat loopback_dev)"
else
	set -e

	guestunmount mountpoint/

	pid="$(cat guestfs.pid)"

	# shellcheck disable=SC2034
	for i in $(seq 10); do
		if ! kill -0 "$pid" 2>/dev/null; then
			break
		fi
		sleep .1
	done

	while kill -0 "$pid" 2>/dev/null; do
		sleep 1
	done
fi
