#!/bin/bash

set -uxe

if [ -n "${USE_LOOPBACK:-}" ]; then
	umount mountpoint/
	losetup -d "$(cat loopback_dev)"
elif [ -n "${USE_DOCKER:-}" ]; then
    docker exec -i -u root:root managarm-mount bash -c "
        set -ex
        sync
        umount /devtmpfs
        umount /mnt
        losetup -d \$(cat loopback_dev)
    "
    docker stop -t 0 managarm-mount
else
	set -e

	guestunmount mountpoint/

	pid="$(cat guestfs.pid)"

	# shellcheck disable=SC2034
	for i in $(seq 10); do
		if ! kill -0 "$pid" 2>/dev/null; then
			break
		fi
		sleep .1
	done

	while kill -0 "$pid" 2>/dev/null; do
		sleep 1
	done
fi
